import numpy as np

CAM_W = 640
CAM_H = 480

DEFAULT_LOWER_SKIN = np.array([0, 23, 141])
DEFAULT_UPPER_SKIN = np.array([89, 255, 255])

SHIELD_RAD = 60
ENEMY_RAD = 25
ENEMY_SPEED = 7

MAX_HP = 5

SHIELD_ASSET = 'assets/shield.png'
FIREBALL_ASSET = 'assets/fireball.png'
GHAST_ASSET = 'assets/ghast_shooting.png'

SHIELD_SIZE = 120
FIREBALL_SIZE = 60

GHAST_W = 170
GHAST_H = 135
GHAST_Y = 25
GHAST_SPEED = 3
GHAST_MOUTH_OFFSET_X = 40
GHAST_MOUTH_OFFSET_Y = 86

FIREBALL_COOLDOWN = 45
MAX_FIREBALLS = 6

DEFLECT_EFFECT_LIFE = 14
DEFLECT_SPARK_COUNT = 16
DEFLECT_SPARK_SPEED = 9