import numpy as np

CAM_W = 640
CAM_H = 480

DEFAULT_LOWER_SKIN = np.array([0, 23, 141])
DEFAULT_UPPER_SKIN = np.array([89, 255, 255])

SHIELD_RAD = 60
ENEMY_RAD = 25
ENEMY_SPEED = 7

MAX_HP = 5

SHIELD_ASSET = 'assets/shield.png'
FIREBALL_ASSET = 'assets/fireball.png'
GHAST_IDLE_ASSET = 'assets/ghast_idle.gif'
GHAST_SHOOTING_ASSET = 'assets/ghast_shooting.png'
MENU_BACKGROUND_ASSET = 'assets/menu_background.jpg'
MENU_FONT_ASSET = 'assets/fonts/Minecraft.ttf'

SHIELD_SIZE = 120
FIREBALL_SIZE = 60

GHAST_W = 170
GHAST_H = 135
GHAST_Y = 25
GHAST_SPEED = 3

GHAST_MOUTH_OFFSET_X = 40
GHAST_MOUTH_OFFSET_Y = 86

GHAST_SHOOT_DURATION = 32
GHAST_SHOOT_START_DELAY = 8
GHAST_BURST_COUNT = 3
GHAST_BURST_INTERVAL = 7
GHAST_FIREBALL_SPREAD_X = 4

FIREBALL_COOLDOWN = 75
MAX_FIREBALLS = 9

DEFLECT_EFFECT_LIFE = 14
DEFLECT_SPARK_COUNT = 16
DEFLECT_SPARK_SPEED = 9

SCORE_PER_DEFLECT = 10

APP_STATE_MENU = 'menu'
APP_STATE_PLAYING = 'playing'
APP_STATE_QUIT = 'quit'